### PR TITLE
Survey Grid generation improvement. Alternating Lanes

### PR DESCRIPTION
**Pull request by wjax**
- Improve Grid generation by calculating closestLines to point by a
perpendicular proyection
- Add basic new feature to allow user to Alternate lanes. Useful for
plane users as turn radius is increased. No need to overshoot so much

### CODE REVIEW

**Comment by wjax** [comment]
First of more to come additions to improve grid generation for planes.
Following would allow a maximum turning angle and thus calculating lane separation and waypoints order.

**Comment by iskess** [comment]
This was originally requested in #506 and the solution identified as a Zamboni pattern by @RemapHi.

**Comment by wjax** [comment]
Hi iskess

My solution does not use zamboni pattern. I did not know about it until you just pointed me there.
The solution in this pull request allows the user to select the minimum separation (in number of lanes) to be used by Mission Planner to generate the grid to fly.

I have tested it and it works quite well.
I was planning to add a "minimum radius" to the grid generation algorithm so the grid and waypoints dont force an aircraft to do something it cannot acomplish.

**Comment by wjax** [comment]
Take a look

https://drive.google.com/file/d/0BzRzbaLTcOpbeVBwUVFPMktWSVE/view?usp=sharing

**Comment by iskess** [comment]
Jesus,
I like the idea of a minimum radius. Perhaps it could be taken a step further and the user could enter a projected wind velocity. The algorithm will look at the tailwind vector component on the downwind turn, use the cruise speed, use the max bank angle parameter, and calculate the minimum turn radius. Using wind has other advantages, such as identifying the maximum triggering speed to see if we will exceed the camera's capabilities on the downwind leg. There is a good discussion on issue #542 .
As mentioned by @bbasso, it would be very interesting and useful to compare the ground track length of three methods; Yours, Zamboni's, and the current overshoot method. 
Thank you for working on this. There hasn't been any Survey Grid development since @tristannovak  made his great contributions. 

Iam

**Pull request closed without merging**
