### PR TITLE
Video resolution fix

### PR DESCRIPTION
**Pull request by kjeremy**
Fixes video quality issues when using VLC to stream hi-def video and improves HUD rendering performance.

### CODE REVIEW

**Comment by meee1** [comment]
does this code deal with the hud being resized? this is why it was a locked size originally, as i hadn't fixed that yet.

**Comment by kjeremy** [comment]
Yes the HUD resizes just fine with this.  It doesn't alias anymore with this change.  Non power of two textures have been supported since OpenGL 2.0 (2004).  If you want I can add a check and fallback to the resize if the hardware doesn't support it.

**Comment by kjeremy** [comment]
I've added a check for non-power of two texture support that will fall back to the old behavior if unsupported

**Comment by meee1** [comment]
merged thanks

**Pull request closed without merging**
