### PR TITLE
L10N: multiple changes

### PR DESCRIPTION
**Pull request by SkiTiSu**
fix mirror check **[IMPORTANT]**
add mirror replacement for update check
update zh-Hans translation

### CODE REVIEW

**Comment by magicrub** [comment]
Multiple changes is best handled with multiple PRs.

**Comment by SkiTiSu** [comment]
@magicrub OK, I will pay attention next time

**Comment by meee1** [comment]
commited here https://github.com/diydrones/MissionPlanner/commit/97c9dc90549df8d5ea94aa18123c6c1ad0f9b503

**Comment by meee1** [comment]
and ehre
https://github.com/diydrones/MissionPlanner/commit/903217c7ff488c2872dda42af0505f91038a5434

**Pull request closed without merging**
