### PR TITLE
Added PreFlight checks and flight planner buttons added

### PR DESCRIPTION
**Pull request by mwrightE38**
Added Add Polygon, ClearPolygon, ElevationGraph, Clear Mission, and Add Takeoff WP buttons to Flight Plan tab.
flightplannerbuttons

Added the Event38 Preflight CheckList
preflightchecklist

### CODE REVIEW

**Comment by iskess** [comment]
Could you please provide a brief description or screenshot of the changes? Thanks!

**Comment by meee1** [comment]
this pull request needs modifying,
it currently removes multiple recent fixs, such as
SHA-1: 0283e4dc583206105ebec8f2e6cedc46b4b5e13c
* UTMWGS: fix equator bug

I would also suggest removing the .gitattribute file, and setting the line endings via the local git client

**Comment by Jman841** [comment]
I hope this can be cleaned up because I think the preflight checklist is an awesome idea. Although, would it be able to be modified for different airframes or different user requirements in the advanced tab or maybe via Control F?

**Comment by meee1** [comment]
ive now merged part of this, I however plan on making some changes, to make it more generic

**Comment by meee1** [comment]
ive modified the preflight checklist to be adjustable

**Pull request closed without merging**
