### PR TITLE
Log: DoubleClick log item to apply user-defined offset and scalar

### PR DESCRIPTION
**Pull request by magicrub**
When plotting data it is sometimes nice to add a scalar and/or an offset. Good examples are when comparing GPS alt vs baro alt vs lidar alt.
Any DataFlash .bin/.log logged value can have an arbitrary scalar and/or offset applied when plotted.
Enter modifier then value, they are applied in the order you provide. Modifiers are x + - /
Example: Convert cm to to m with an offset of 50: '/100 +50' or 'x0.01 +50' or '*0.01,+50'

### CODE REVIEW

**Comment by magicrub** [comment]
Bump

**Comment by magicrub** [comment]
Michael, Do you have any questions about this that I can answer for you?

**Comment by meee1** [comment]
can I request we use a null check instead of hardcoding default template
ie remove
 dataModifier = new DataModifer("x1+0");

this will improve performance than the current method.

**Comment by magicrub** [comment]
Sure. I can do the edit tomorrow or the day after unless you beat me to it.

**Comment by magicrub** [comment]
Done!

**Comment by meee1** [comment]
merged

**Pull request closed without merging**
